// GENERATED by scripts/dump-datapack.ts - one import per data file.
// Add a new file? Add its import here (or re-run the generator).
import d0 from "./zombie.json";
import d1 from "./skeleton.json";
import d2 from "./creeper.json";
import d3 from "./zombified_piglin.json";
import d4 from "./pig.json";
import d5 from "./cow.json";
import d6 from "./sheep.json";
import d7 from "./chicken.json";
import d8 from "./villager.json";

export const MOB_JSONS: unknown[] = [d0, d1, d2, d3, d4, d5, d6, d7, d8];
